/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "surface-bright": "#fcf8ff",
        "on-surface-variant": "#464555",
        "tertiary-fixed-dim": "#ffb695",
        secondary: "#9a442d",
        "on-secondary-container": "#742814",
        "surface-container": "#efecff",
        "on-primary": "#ffffff",
        background: "#fcf8ff",
        "primary-fixed": "#e2dfff",
        "primary-container": "#4f46e5",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-error": "#ffffff",
        "secondary-container": "#fc9174",
        "tertiary-container": "#a44100",
        "surface-tint": "#4d44e3",
        "surface-container-highest": "#e3e0f7",
        outline: "#777587",
        "primary-fixed-dim": "#c3c0ff",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1a1a2a",
        "on-primary-fixed": "#0f0069",
        "surface-container-low": "#f5f2ff",
        "outline-variant": "#c7c4d8",
        "inverse-primary": "#c3c0ff",
        "surface-container-high": "#e8e6fc",
        "on-surface": "#1a1a2a",
        tertiary: "#7e3000",
        "inverse-surface": "#2f2f40",
        primary: "#3525cd",
        "surface-dim": "#dad8ee",
        "secondary-fixed": "#ffdbd2",
        "on-tertiary-fixed": "#351000",
        "on-secondary": "#ffffff",
        "on-primary-container": "#dad7ff",
        "on-secondary-fixed": "#3c0800",
        "inverse-on-surface": "#f2efff",
        "on-secondary-fixed-variant": "#7c2e19",
        "error-container": "#ffdad6",
        "surface-variant": "#e3e0f7",
        "tertiary-fixed": "#ffdbcc",
        "on-tertiary-container": "#ffd2be",
        error: "#ba1a1a",
        surface: "#fcf8ff",
        "on-primary-fixed-variant": "#3323cc",
        "secondary-fixed-dim": "#ffb4a1",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "24px",
        lg: "48px",
        xs: "4px",
        xl: "80px",
        gutter: "24px",
        base: "8px",
        sm: "12px",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-small": ["Inter"],
        h2: ["Inter"],
        "label-caps": ["Inter"],
        "body-large": ["Inter"],
        h3: ["Inter"],
        "h1-desktop": ["Inter"],
        "h1-mobile": ["Inter"],
      },
      fontSize: {
        "body-small": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        h2: [
          "28px",
          { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-large": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        h3: ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "h1-desktop": [
          "36px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "h1-mobile": [
          "28px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};
